### PR TITLE
fix SSR scenarios,  converting SVG to a string ,In this context, the associated lifecycle hooks are not executed

### PR DESCRIPTION
**Pull request by loycoder**
I tried to fix an issue where rendering SVG with renderToString was empty,
This is my first time submitting a PR request，If there is any unreasonable, please give suggestions.

### CODE REVIEW

**Comment by loycoder** [comment]
this is codeSanbox demo :
https://codesandbox.io/s/react-inlinesvg-demo-forked-hy859x?file=/src/index.tsx

**Comment by gilbarbara** [comment]
hey @loycoder 

Thanks for your submission, but as stated in the [CONTRIBUTING](https://github.com/gilbarbara/react-inlinesvg/blob/main/CONTRIBUTING.md) guide, we expect to discuss new features in the issues before committing code.

This PR only covers inline `src` and it was added to cover some edge cases.
If you already have the SVG code why not render it directly instead of using a library?

What do you mean by "the associated lifecycle hooks are not executed"? since you only changed the render function?

**Comment by loycoder** [comment]
> 嘿@loycoder
> 
> 感谢您的提交，但正如[CONTRIBUTING](https://github.com/gilbarbara/react-inlinesvg/blob/main/CONTRIBUTING.md)指南中所述，我们希望在提交代码之前讨论问题中的新功能。
> 
> 此 PR 仅涵盖内联`src`，并添加它以涵盖一些边缘情况。 如果您已经有了 SVG 代码，为什么不直接渲染它而不是使用库呢？
> 
> “未执行相关的生命周期挂钩”是什么意思？因为你只改变了渲染功能？



> hey @loycoder
> 
> Thanks for your submission, but as stated in the [CONTRIBUTING](https://github.com/gilbarbara/react-inlinesvg/blob/main/CONTRIBUTING.md) guide, we expect to discuss new features in the issues before committing code.
> 
> This PR only covers inline `src` and it was added to cover some edge cases. If you already have the SVG code why not render it directly instead of using a library?
> 
> What do you mean by "the associated lifecycle hooks are not executed"? since you only changed the render function?

@gilbarbara

**Comment by loycoder** [comment]
> hey @loycoder
> 
> Thanks for your submission, but as stated in the [CONTRIBUTING](https://github.com/gilbarbara/react-inlinesvg/blob/main/CONTRIBUTING.md) guide, we expect to discuss new features in the issues before committing code.
> 
> This PR only covers inline `src` and it was added to cover some edge cases. If you already have the SVG code why not render it directly instead of using a library?
> 
> What do you mean by "the associated lifecycle hooks are not executed"? since you only changed the render function?

@gilbarbara ， Thank you for your reply. I have been inspired and come up with new ideas
When renderToString returns null, I can use the Loader argument to replace the code I changed， Like this：
```js
<SVG
      className={className}
      src={Icon}
      stroke={stroke}
      loader={convertSvgToReactNode(Icon)}
    />

```

**Pull request closed without merging**
