### PR TITLE
 Only render current src

### PR DESCRIPTION
**Pull request by Robinfr**
There was a bug where if you would change the `src` prop multiple times
and the first `src` was cached and the second `src` wasn't, the first
`src` would be rendered instead.

I've added a check whether the loaded source is still the current
source.

### CODE REVIEW

**Comment by gilbarbara** [comment]
maybe use the `src` filename as a key would be a better option?

**Comment by Robinfr** [comment]
That would fix it also, but shouldn't be required. This library is literally rendering the wrong thing in this situation.

**Comment by gilbarbara** [comment]
I meant in the wrapper, unless the user sets the key by itself.

**Comment by gilbarbara** [comment]
Please remove the package and lock so I can merge it.

**Comment by Robinfr** [comment]
@gilbarbara done.

**Pull request merged**
