### PR TITLE
Fix bug where assets are not immediately cached

### PR DESCRIPTION
**Pull request by Joroze**
This addresses a bug I've found where:

1. Render a list of `react-svginline` components with `src` property set to the same URL string value and `cacheRequests` property set to `true` boolean.
2. Each `react-svginline` component unexpectedly requests the same SVG asset because there is no immediate sync caching of url and loading status.

This pull request will introduce the following changes:
- Bug fix for caching (when enabled) where we will now make only 1 GET request per cached `src` prop URL value and queue up other to-be-loaded instances that have the same `src` prop URL value. If the request is resolved successfully, go through each item in the cache queue to load the rest of the svgs of the same content.

- Optimization and refactor of cache data structure from O(n) to O(1) time complexity

- Introduce feature for https://github.com/gilbarbara/react-inlinesvg/issues/100 since it is related

- Updated tests

### CODE REVIEW

**Comment by gilbarbara** [comment]
Hey @Joroze,
Sorry, I didn't have time to look at this before.

Your PR changed too much code (including package fields?!), so I can't accept it.
I'm working in a new cache system and I'll add some of the changes you proposed.
Thanks anyway!

**Comment by Joroze** [comment]
Hi @gilbarbara,

I should have split some of my code into different pull requests. I apologize about that. 

FYI: The changes to the package.json seems to be commits made by you in the month of May.

Thanks for taking some of my cache system suggestions! I love your work.

**Comment by gilbarbara** [comment]
I meant changing the keywords and peerDependencies in the package.json. Besides isn't a good practice to change package versions mixed with code changes since it can cause conflicts.

Thanks! <3
I hope to finish by the end of the week.

**Comment by Joroze** [comment]
Interesting. Good to know! I'm not sure how your commit with the package field changes got squeezed into my PR. 

https://github.com/gilbarbara/react-inlinesvg/pull/113/commits/f5f6377ee699c112f842c8cc426da68f7f9d2285


And awesome. Can't wait.

**Comment by gilbarbara** [comment]
Aww, sorry about that. I've rebased the `next` branch and that's why things got messy. 😐

**Pull request closed without merging**
